FROM node:20-alpine

WORKDIR /app

# chỉ copy package trước để cache
COPY package*.json ./

RUN npm install --legacy-peer-deps

# sau đó mới copy source
COPY . .

EXPOSE 3005

CMD ["npm", "run", "start"]