FROM node:20-alpine

WORKDIR /app

# copy package trước để cache
COPY package*.json ./

# FIX: dùng install thay vì ci
RUN npm install --legacy-peer-deps

# copy source
COPY . .

# build nếu có
RUN npm run build || echo "skip build"

EXPOSE 3005

CMD ["node", "dist/main.js"]