FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/
RUN npm install --legacy-peer-deps --include=dev

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]