# FROM node:20-alpine

# WORKDIR /app

# # chỉ copy package trước để cache
# COPY package*.json ./

# RUN npm install --legacy-peer-deps

# # sau đó mới copy source
# COPY . .
# RUN npm run build
# EXPOSE 3000

# CMD ["npm", "run", "start"]

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

# Copy static assets vào đúng chỗ standalone cần
RUN cp -r .next/static .next/standalone/.next/static && \
    cp -r public .next/standalone/public

EXPOSE 3000

# ✅ Đúng với output: standalone
CMD ["node", ".next/standalone/server.js"]