version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: tour-mongodb
    ports:
      - "27017:27017"
    networks:
      - tour-network

  api-gateway:
    build: ./services/api-gateway
    image: mnhat1/api-gateway:latest
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - users-service
    networks:
      - tour-network

  auth-service:
    build: ./services/auth-service
    image: mnhat1/auth-service:latest
    ports:
      - "3002:3002"
    networks:
      - tour-network

  users-service:
    build: ./services/users-service
    image: mnhat1/users-service:latest
    ports:
      - "3001:3001"
    networks:
      - tour-network

  tours-service:
    build: ./services/tours-service
    image: mnhat1/tours-service:latest
    ports:
      - "3003:3003"
    networks:
      - tour-network

  bookings-service:
    build: ./services/bookings-service
    image: mnhat1/bookings-service:latest
    ports:
      - "3004:3004"
    networks:
      - tour-network

  reviews-service:
    build: ./services/reviews-service
    image: mnhat1/reviews-service:latest
    ports:
      - "3005:3005"
    networks:
      - tour-network

  blog-service:
    build: ./services/blog-service
    image: mnhat1/blog-service:latest
    ports:
      - "3006:3006"
    networks:
      - tour-network

  chat-service:
    build: ./services/chat-service
    image: mnhat1/chat-service:latest
    ports:
      - "3007:3007"
    networks:
      - tour-network

  frontend:
    build: ./frontend
    image: mnhat1/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - tour-network

networks:
  tour-network:
    driver: bridge