services:
  api-gateway:
    build: ./services/api-gateway
    image: mnhat1/api-gateway:${IMAGE_TAG}

  auth-service:
    build: ./services/auth-service
    image: mnhat1/auth-service:${IMAGE_TAG}

  users-service:
    build: ./services/users-service
    image: mnhat1/users-service:${IMAGE_TAG}

  tours-service:
    build: ./services/tours-service
    image: mnhat1/tours-service:${IMAGE_TAG}

  bookings-service:
    build: ./services/bookings-service
    image: mnhat1/bookings-service:${IMAGE_TAG}

  reviews-service:
    build: ./services/reviews-service
    image: mnhat1/reviews-service:${IMAGE_TAG}

  blog-service:
    build: ./services/blog-service
    image: mnhat1/blog-service:${IMAGE_TAG}

  chat-service:
    build: ./services/chat-service
    image: mnhat1/chat-service:${IMAGE_TAG}

  frontend:
    build: ./frontend
    image: mnhat1/frontend:${IMAGE_TAG}