# Development stage
FROM node:20-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
USER node

# Production stage
FROM node:20-alpine AS production
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000
RUN npm install --legacy-peer-deps --only=production && npm cache clean --force
COPY --from=development /usr/src/app/dist ./dist
USER node

EXPOSE 4000
CMD ["node", "dist/main.js"]