FROM node:20-alpine

WORKDIR /app

# chỉ copy package trước để cache
COPY package*.json ./

RUN npm install --legacy-peer-deps

# sau đó mới copy source
COPY . .
RUN npm run build
EXPOSE 3001

CMD ["npm", "run", "start"]