FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000

RUN npm install --legacy-peer-deps

COPY . .

# ❗ Không build để tránh fail CI
# RUN npm run build

EXPOSE 3002

CMD ["npm", "run", "start"]